# Generated by Django 4.0.4 on 2022-06-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='store _cust_last_na_6a8810_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='store _customer',
        ),
    ]
